### ISSUE TITLE
upload screening sheet

### ISSUE THREAD

**Issue by SpaceInhabitant** [tailoringexpert/plattform#182]
After the selection and uploading a screening sheet none of the fields will be greyed out. This creates the impression that a screeningsheet can be uploaded again without having to leave the web page.
Such functionality can be useful when it is discovered that inputs are incorrect and need to be corrected.
After the correction of the inputs in the screening sheet one need only to click again on the button "upload".
However, the upload of the screening sheet is restarted after pressing the upload button again, but not completed. The corrected data are neither transferred nor displayed.

It is expected that the corrected data are transferred and displayed.

**Comment by baedorf** [comment]
Editing a screeningsheet is not implemented in the tailoring platform.  The platform _only _uploads_ and parses the provided screeningsheet, but does not edit it. This is out of scope.
Please use your usual tools, save your screeningsheet and upload the desired file.
