### ISSUE TITLE
Embedding images in requirements

### ISSUE THREAD

**Issue by SpaceInhabitant** [tailoringexpert/plattform#183]
Editing a requirement:
A dialogue appears for entering a URL to the image to be included.
Entering a path to a local stored image does not yield the expected outcome: The image is not displayed.

It is not explained which format the URL/path to the image file must have.

It is expected that locally stored images can be uploaded and are displayed correctly.

**Comment by baedorf** [comment]
It is not intended to implement an upload function for images.
There are several reasons for this:
Images would need to be added to a catalogue version and not to a tailoring. The resources for the catalogue are located in the web server part of the platform. The application server part, at least at present, does not have its own  information about where to find these resources. This information is contained in the requirement texts.
To add images to a request, the name of the image must be known. It is not intended to implement a file browser for this.
Similarly, the icon in the user interface also only adds a link and is not intended to upload a file and then reference it. This is plugin behaviour. If something else is desired, anyone can fork the [web ](https://github.com/tailoringexpert/web)project and provide a custom implementation for it.
